import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function seed() {
  await prisma.anislag.createMany({
    data: [
      {
        assessor_no: 1,
        cadastral_no: '9001 A',
        arp_A: '10001',
        arp_B: null,
        arp_C: null,
        arp_D: '20001',
        arp_E: null,
        name_owner: 'MARIA POBLACIONA',
        title_no: 'T-1001',
        area: '1.1000',
        classification_no: 'A',
        improvement_1: '1',
        improvement_2: '1001',
        mch: null,
        oth: null,
        
        index_no: '001-001',
        barangay: 'POBLACION',
        cancel_reason: null,
        cancel_details: null,
      },
      {
        assessor_no: 2,
        cadastral_no: '9002 B',
        arp_A: '10002',
        arp_B: null,
        arp_C: null,
        arp_D: '20002',
        arp_E: null,
        name_owner: 'JOSE POBLACION',
        title_no: 'T-1002',
        area: '1.2000',
        classification_no: 'A/R',
        improvement_1: '2',
        improvement_2: '1002',
        mch: null,
        oth: null,
        
        index_no: '001-001',
        barangay: 'POBLACION',
        cancel_reason: null,
        cancel_details: null,
      },
      {
        assessor_no: 3,
        cadastral_no: '8003 A',
        arp_A: '11001',
        arp_B: null,
        arp_C: '13001',
        arp_D: null,
        arp_E: '15001',
        name_owner: 'LUIS ANISLAGO',
        title_no: 'T-2001',
        area: '1.3000',
        classification_no: 'A',
        improvement_1: '1',
        improvement_2: '1101',
        mch: null,
        oth: null,
        
        index_no: '002-001',
        barangay: 'ANISLAG',
        cancel_reason: null,
        cancel_details: null,
      },
      {
        assessor_no: 4,
        cadastral_no: '8004 B',
        arp_A: null,
        arp_B: '12001',
        arp_C: null,
        arp_D: '14001',
        arp_E: null,
        name_owner: 'ANITA ANISLAG',
        title_no: 'T-2002',
        area: '1.4000',
        classification_no: 'A/R',
        improvement_1: '2',
        improvement_2: '1201',
        mch: null,
        oth: null,
        
        index_no: '002-001',
        barangay: 'ANISLAG',
        cancel_reason: null,
        cancel_details: null,
      },
      {
        assessor_no: 5,
        cadastral_no: '8005 C',
        arp_A: '11002',
        arp_B: null,
        arp_C: '13002',
        arp_D: null,
        arp_E: '15002',
        name_owner: 'CARLOS REYES',
        title_no: 'T-3001',
        area: '1.5000',
        classification_no: 'A',
        improvement_1: '3',
        improvement_2: '1302',
        mch: null,
        oth: null,
        
        index_no: '002-002',
        barangay: 'ANISLAG',
        cancel_reason: null,
        cancel_details: null,
      },
      {
        assessor_no: 6,
        cadastral_no: '8006 D',
        arp_A: '11003',
        arp_B: '12003',
        arp_C: null,
        arp_D: '14003',
        arp_E: null,
        name_owner: 'GABRIEL SANTOS',
        title_no: 'T-3002',
        area: '1.6000',
        classification_no: 'A/R',
        improvement_1: '1',
        improvement_2: '1403',
        mch: null,
        oth: null,
        
        index_no: '002-002',
        barangay: 'ANISLAG',
        cancel_reason: null,
        cancel_details: null,
      },
      {
        assessor_no: 7,
        cadastral_no: '8007 E',
        arp_A: null,
        arp_B: null,
        arp_C: '13003',
        arp_D: '14004',
        arp_E: '15003',
        name_owner: 'FERNANDO LOPEZ',
        title_no: 'T-3003',
        area: '1.7000',
        classification_no: 'A',
        improvement_1: '2',
        improvement_2: '1503',
        mch: null,
        oth: null,
        
        index_no: '002-002',
        barangay: 'ANISLAG',
        cancel_reason: null,
        cancel_details: null,
      },
      {
        assessor_no: 8,
        cadastral_no: '8008 F',
        arp_A: '11004',
        arp_B: null,
        arp_C: null,
        arp_D: '14005',
        arp_E: '15004',
        name_owner: 'RICARDO ALVAREZ',
        title_no: 'T-3004',
        area: '1.8000',
        classification_no: 'A',
        improvement_1: '1',
        improvement_2: '1601',
        mch: null,
        oth: null,
        
        index_no: '002-002',
        barangay: 'ANISLAG',
        cancel_reason: null,
        cancel_details: null,
      },
      {
        assessor_no: 9,
        cadastral_no: '8009 G',
        arp_A: '11005',
        arp_B: '12005',
        arp_C: '13005',
        arp_D: null,
        arp_E: null,
        name_owner: 'ISABEL RAMOS',
        title_no: 'T-3005',
        area: '2.0000',
        classification_no: 'A/R',
        improvement_1: '2',
        improvement_2: '1701',
        mch: null,
        oth: null,
        
        index_no: '002-002',
        barangay: 'ANISLAG',
        cancel_reason: null,
        cancel_details: null,
      },
      {
        assessor_no: 10,
        cadastral_no: '8010 H',
        arp_A: '11006',
        arp_B: null,
        arp_C: null,
        arp_D: '14006',
        arp_E: '15005',
        name_owner: 'LORENZO VILLAR',
        title_no: 'T-4001',
        area: '2.1000',
        classification_no: 'A',
        improvement_1: '3',
        improvement_2: '1801',
        mch: null,
        oth: null,
        
        index_no: '002-003',
        barangay: 'ANISLAG',
        cancel_reason: null,
        cancel_details: null,
      },
      {
        assessor_no: 11,
        cadastral_no: '8011 I',
        arp_A: '11007',
        arp_B: null,
        arp_C: '13006',
        arp_D: '14007',
        arp_E: null,
        name_owner: 'ANGELA MORALES',
        title_no: 'T-4002',
        area: '2.2000',
        classification_no: 'A/R',
        improvement_1: '1',
        improvement_2: '1901',
        mch: null,
        oth: null,
        
        index_no: '002-003',
        barangay: 'ANISLAG',
        cancel_reason: null,
        cancel_details: null,
      },
      {
        assessor_no: 12,
        cadastral_no: '8012 J',
        arp_A: null,
        arp_B: '12007',
        arp_C: null,
        arp_D: null,
        arp_E: '15006',
        name_owner: 'PEDRO GARCIA',
        title_no: 'T-4003',
        area: '2.3000',
        classification_no: 'A',
        improvement_1: '2',
        improvement_2: '2001',
        mch: null,
        oth: null,
        
        index_no: '002-003',
        barangay: 'ANISLAG',
        cancel_reason: null,
        cancel_details: null,
      },
      {
        assessor_no: 13,
        cadastral_no: '8013 K',
        arp_A: '11008',
        arp_B: null,
        arp_C: null,
        arp_D: '14008',
        arp_E: '15007',
        name_owner: 'ROGELIO SISON',
        title_no: 'T-5001',
        area: '2.4000',
        classification_no: 'A',
        improvement_1: '3',
        improvement_2: '2101',
        mch: null,
        oth: null,
        
        index_no: '002-004',
        barangay: 'ANISLAG',
        cancel_reason: null,
        cancel_details: null,
      },
      {
        assessor_no: 14,
        cadastral_no: '8014 L',
        arp_A: '11009',
        arp_B: '12008',
        arp_C: '13007',
        arp_D: null,
        arp_E: null,
        name_owner: 'GENEVIEVE TOLENTINO',
        title_no: 'T-5002',
        area: '2.5000',
        classification_no: 'A/R',
        improvement_1: '1',
        improvement_2: '2201',
        mch: null,
        oth: null,
        
        index_no: '002-004',
        barangay: 'ANISLAG',
        cancel_reason: null,
        cancel_details: null,
      },
    ]
    
  });


  console.log('✅ Seed data inserted!');
}

seed()
  .catch((e) => {
    console.error('❌ Error in seed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
